// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'ffi.dart' as ffi;
import 'interop.dart';

extension IDRISDBBindingsX on JSIDRISDB {
  @ffi.Native<
    ffi.Pointer<CString> Function(ffi.Pointer<ffi.Uint16>, ffi.Uint32)
  >(symbol: 'IDRISDB_string')
  external ffi.Pointer<CString> IDRISDB_string(
    ffi.Pointer<ffi.Uint16> chars,
    int length,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CString>)>(
    symbol: 'IDRISDB_string_free',
  )
  external void IDRISDB_string_free(ffi.Pointer<CString> value);

  @ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32)>(
    symbol: 'IDRISDB_buffer_free',
  )
  external void IDRISDB_buffer_free(ffi.Pointer<ffi.Uint8> value, int capacity);

  @ffi.Native<ffi.Uint32 Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>)>(
    symbol: 'IDRISDB_get_error',
  )
  external int IDRISDB_get_error(ffi.Pointer<ffi.Pointer<ffi.Uint8>> value);

  @ffi.Native<
    ffi.Pointer<CIdrisDbReader> Function(
      ffi.Pointer<CIDRISDBCursor>,
      IDRISDBI64,
      ffi.Pointer<CIdrisDbReader>,
    )
  >(symbol: 'IDRISDB_cursor_next')
  external ffi.Pointer<CIdrisDbReader> IDRISDB_cursor_next(
    ffi.Pointer<CIDRISDBCursor> cursor,
    int id,
    ffi.Pointer<CIdrisDbReader> old_reader,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIDRISDBCursor>, ffi.Pointer<CIdrisDbReader>)
  >(symbol: 'IDRISDB_cursor_free')
  external void IDRISDB_cursor_free(
    ffi.Pointer<CIDRISDBCursor> cursor,
    ffi.Pointer<CIdrisDbReader> reader,
  );

  @ffi.Native<
    ffi.Pointer<CIdrisDbReader> Function(
      ffi.Pointer<CIdrisDbQueryCursor>,
      ffi.Pointer<CIdrisDbReader>,
    )
  >(symbol: 'IDRISDB_query_cursor_next')
  external ffi.Pointer<CIdrisDbReader> IDRISDB_query_cursor_next(
    ffi.Pointer<CIdrisDbQueryCursor> cursor,
    ffi.Pointer<CIdrisDbReader> old_reader,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbQueryCursor>, ffi.Pointer<CIdrisDbReader>)
  >(symbol: 'IDRISDB_query_cursor_free')
  external void IDRISDB_query_cursor_free(
    ffi.Pointer<CIdrisDbQueryCursor> cursor,
    ffi.Pointer<CIdrisDbReader> reader,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
    symbol: 'IDRISDB_connect_dart_api',
  )
  external void IDRISDB_connect_dart_api(ffi.Pointer<ffi.Void> ptr);

  @ffi.Native<ffi.Pointer<CFilter> Function(ffi.Uint16)>(
    symbol: 'IDRISDB_filter_is_null',
  )
  external ffi.Pointer<CFilter> IDRISDB_filter_is_null(int property_index);

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_equal')
  external ffi.Pointer<CFilter> IDRISDB_filter_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_greater')
  external ffi.Pointer<CFilter> IDRISDB_filter_greater(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_greater_or_equal')
  external ffi.Pointer<CFilter> IDRISDB_filter_greater_or_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_less')
  external ffi.Pointer<CFilter> IDRISDB_filter_less(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_less_or_equal')
  external ffi.Pointer<CFilter> IDRISDB_filter_less_or_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(
      ffi.Uint16,
      ffi.Pointer<CIDRISDBValue>,
      ffi.Pointer<CIDRISDBValue>,
      ffi.Bool,
    )
  >(symbol: 'IDRISDB_filter_between')
  external ffi.Pointer<CFilter> IDRISDB_filter_between(
    int property_index,
    ffi.Pointer<CIDRISDBValue> lower,
    ffi.Pointer<CIDRISDBValue> upper,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_string_starts_with')
  external ffi.Pointer<CFilter> IDRISDB_filter_string_starts_with(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_string_ends_with')
  external ffi.Pointer<CFilter> IDRISDB_filter_string_ends_with(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_string_contains')
  external ffi.Pointer<CFilter> IDRISDB_filter_string_contains(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CIDRISDBValue>, ffi.Bool)
  >(symbol: 'IDRISDB_filter_string_matches')
  external ffi.Pointer<CFilter> IDRISDB_filter_string_matches(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  );

  @ffi.Native<ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CFilter>)>(
    symbol: 'IDRISDB_filter_nested',
  )
  external ffi.Pointer<CFilter> IDRISDB_filter_nested(
    int property_index,
    ffi.Pointer<CFilter> filter,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Pointer<ffi.Pointer<CFilter>>, ffi.Uint32)
  >(symbol: 'IDRISDB_filter_and')
  external ffi.Pointer<CFilter> IDRISDB_filter_and(
    ffi.Pointer<ffi.Pointer<CFilter>> filters,
    int lenght,
  );

  @ffi.Native<
    ffi.Pointer<CFilter> Function(ffi.Pointer<ffi.Pointer<CFilter>>, ffi.Uint32)
  >(symbol: 'IDRISDB_filter_or')
  external ffi.Pointer<CFilter> IDRISDB_filter_or(
    ffi.Pointer<ffi.Pointer<CFilter>> filters,
    int lenght,
  );

  @ffi.Native<ffi.Pointer<CFilter> Function(ffi.Pointer<CFilter>)>(
    symbol: 'IDRISDB_filter_not',
  )
  external ffi.Pointer<CFilter> IDRISDB_filter_not(ffi.Pointer<CFilter> filter);

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      ffi.Uint32,
      ffi.Pointer<ffi.Pointer<CIdrisDbWriter>>,
    )
  >(symbol: 'IDRISDB_insert')
  external int IDRISDB_insert(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int count,
    ffi.Pointer<ffi.Pointer<CIdrisDbWriter>> insert,
  );

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIdrisDbWriter>, IDRISDBI64)>(
    symbol: 'IDRISDB_insert_save',
  )
  external int IDRISDB_insert_save(ffi.Pointer<CIdrisDbWriter> insert, int id);

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbWriter>,
      ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
    )
  >(symbol: 'IDRISDB_insert_finish')
  external int IDRISDB_insert_finish(
    ffi.Pointer<CIdrisDbWriter> insert,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIdrisDbWriter>)>(
    symbol: 'IDRISDB_insert_abort',
  )
  external void IDRISDB_insert_abort(ffi.Pointer<CIdrisDbWriter> insert);

  @ffi.Native<ffi.Pointer<ffi.Char> Function()>(symbol: 'IDRISDB_version')
  external ffi.Pointer<ffi.Char> IDRISDB_version();

  @ffi.Native<ffi.Pointer<CIdrisDbInstance> Function(ffi.Uint32, ffi.Bool)>(
    symbol: 'IDRISDB_get_instance',
  )
  external ffi.Pointer<CIdrisDbInstance> IDRISDB_get_instance(
    int instance_id,
    bool sqlite,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<ffi.Pointer<CIdrisDbInstance>>,
      ffi.Uint32,
      ffi.Pointer<CString>,
      ffi.Pointer<CString>,
      ffi.Bool,
      ffi.Pointer<CString>,
      ffi.Uint32,
      ffi.Pointer<CString>,
      ffi.Uint32,
      ffi.Uint32,
      ffi.Float,
    )
  >(symbol: 'IDRISDB_open_instance')
  external int IDRISDB_open_instance(
    ffi.Pointer<ffi.Pointer<CIdrisDbInstance>> IdrisDb,
    int instance_id,
    ffi.Pointer<CString> name,
    ffi.Pointer<CString> path,
    bool sqlite,
    ffi.Pointer<CString> schema_json,
    int max_size_mib,
    ffi.Pointer<CString> encryption_key,
    int compact_min_file_size,
    int compact_min_bytes,
    double compact_min_ratio,
  );

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    )
  >(symbol: 'IDRISDB_get_name')
  external int IDRISDB_get_name(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> name,
  );

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    )
  >(symbol: 'IDRISDB_get_dir')
  external int IDRISDB_get_dir(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> dir,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
      ffi.Bool,
    )
  >(symbol: 'IDRISDB_txn_begin')
  external int IDRISDB_txn_begin(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
    bool write,
  );

  @ffi.Native<
    ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
  >(symbol: 'IDRISDB_txn_commit')
  external int IDRISDB_txn_commit(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
  >(symbol: 'IDRISDB_txn_abort')
  external void IDRISDB_txn_abort(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
  );

  @ffi.Native<IDRISDBI64 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Uint16)>(
    symbol: 'IDRISDB_auto_increment',
  )
  external int IDRISDB_auto_increment(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      ffi.Pointer<ffi.Pointer<CIDRISDBCursor>>,
    )
  >(symbol: 'IDRISDB_cursor')
  external int IDRISDB_cursor(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBCursor>> cursor,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      IDRISDBI64,
      ffi.Pointer<ffi.Bool>,
    )
  >(symbol: 'IDRISDB_delete')
  external int IDRISDB_delete(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int id,
    ffi.Pointer<ffi.Bool> deleted,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      ffi.Pointer<ffi.Uint32>,
    )
  >(symbol: 'IDRISDB_count')
  external int IDRISDB_count(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    ffi.Pointer<ffi.Uint32> count,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
    )
  >(symbol: 'IDRISDB_clear')
  external int IDRISDB_clear(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
  );

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      ffi.Bool,
    )
  >(symbol: 'IDRISDB_get_size')
  external int IDRISDB_get_size(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    bool include_indexes,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
      ffi.Uint16,
      ffi.Pointer<CString>,
      ffi.Pointer<ffi.Uint32>,
    )
  >(symbol: 'IDRISDB_import_json')
  external int IDRISDB_import_json(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
    int collection_index,
    ffi.Pointer<CString> json,
    ffi.Pointer<ffi.Uint32> count,
  );

  @ffi.Native<
    ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CString>)
  >(symbol: 'IDRISDB_copy')
  external int IDRISDB_copy(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CString> path,
  );

  @ffi.Native<
    ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
  >(symbol: 'IDRISDB_verify')
  external int IDRISDB_verify(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
  );

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Bool)>(
    symbol: 'IDRISDB_close',
  )
  external int IDRISDB_close(ffi.Pointer<CIdrisDbInstance> IdrisDb, bool delete_);

  @ffi.Native<
    ffi.Uint8 Function(ffi.Pointer<CString>, ffi.Pointer<CString>, ffi.Bool)
  >(symbol: 'IDRISDB_delete_database')
  external int IDRISDB_delete_database(
    ffi.Pointer<CString> name,
    ffi.Pointer<CString> path,
    bool sqlite,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Uint16,
      ffi.Pointer<ffi.Pointer<CIDRISDBQueryBuilder>>,
    )
  >(symbol: 'IDRISDB_query_new')
  external int IDRISDB_query_new(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBQueryBuilder>> query_builder,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIDRISDBQueryBuilder>, ffi.Pointer<CFilter>)
  >(symbol: 'IDRISDB_query_set_filter')
  external void IDRISDB_query_set_filter(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    ffi.Pointer<CFilter> filter,
  );

  @ffi.Native<
    ffi.Void Function(
      ffi.Pointer<CIDRISDBQueryBuilder>,
      ffi.Uint16,
      ffi.Bool,
      ffi.Bool,
    )
  >(symbol: 'IDRISDB_query_add_sort')
  external void IDRISDB_query_add_sort(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    int property_index,
    bool ascending,
    bool case_sensitive,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIDRISDBQueryBuilder>, ffi.Uint16, ffi.Bool)
  >(symbol: 'IDRISDB_query_add_distinct')
  external void IDRISDB_query_add_distinct(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    int property_index,
    bool case_sensitive,
  );

  @ffi.Native<ffi.Pointer<CIDRISDBQuery> Function(ffi.Pointer<CIDRISDBQueryBuilder>)>(
    symbol: 'IDRISDB_query_build',
  )
  external ffi.Pointer<CIDRISDBQuery> IDRISDB_query_build(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Pointer<CIDRISDBQuery>,
      ffi.Pointer<ffi.Pointer<CIdrisDbQueryCursor>>,
      ffi.Uint32,
      ffi.Uint32,
    )
  >(symbol: 'IDRISDB_query_cursor')
  external int IDRISDB_query_cursor(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    ffi.Pointer<ffi.Pointer<CIdrisDbQueryCursor>> cursor,
    int offset,
    int limit,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Pointer<CIDRISDBQuery>,
      ffi.Uint8,
      ffi.Uint16,
      ffi.Pointer<ffi.Pointer<CIDRISDBValue>>,
    )
  >(symbol: 'IDRISDB_query_aggregate')
  external int IDRISDB_query_aggregate(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int aggregation,
    int property_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBValue>> value,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Pointer<CIDRISDBQuery>,
      ffi.Uint32,
      ffi.Uint32,
      ffi.Pointer<ffi.Uint32>,
    )
  >(symbol: 'IDRISDB_query_delete')
  external int IDRISDB_query_delete(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int offset,
    int limit,
    ffi.Pointer<ffi.Uint32> count,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIDRISDBQuery>)>(
    symbol: 'IDRISDB_query_free',
  )
  external void IDRISDB_query_free(ffi.Pointer<CIDRISDBQuery> query);

  @ffi.Native<IDRISDBI64 Function(ffi.Pointer<CIdrisDbReader>)>(
    symbol: 'IDRISDB_read_id',
  )
  external int IDRISDB_read_id(ffi.Pointer<CIdrisDbReader> reader);

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_null',
  )
  external int IDRISDB_read_null(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_bool',
  )
  external int IDRISDB_read_bool(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_byte',
  )
  external int IDRISDB_read_byte(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<ffi.Int32 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_int',
  )
  external int IDRISDB_read_int(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<ffi.Float Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_float',
  )
  external double IDRISDB_read_float(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<IDRISDBI64 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_long',
  )
  external int IDRISDB_read_long(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<ffi.Double Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)>(
    symbol: 'IDRISDB_read_double',
  )
  external double IDRISDB_read_double(ffi.Pointer<CIdrisDbReader> reader, int index);

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbReader>,
      ffi.Uint32,
      ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      ffi.Pointer<ffi.Bool>,
    )
  >(symbol: 'IDRISDB_read_string')
  external int IDRISDB_read_string(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> value,
    ffi.Pointer<ffi.Bool> is_ascii,
  );

  @ffi.Native<
    ffi.Pointer<CIdrisDbReader> Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
  >(symbol: 'IDRISDB_read_object')
  external ffi.Pointer<CIdrisDbReader> IDRISDB_read_object(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
  );

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbReader>,
      ffi.Uint32,
      ffi.Pointer<ffi.Pointer<CIdrisDbReader>>,
    )
  >(symbol: 'IDRISDB_read_list')
  external int IDRISDB_read_list(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
    ffi.Pointer<ffi.Pointer<CIdrisDbReader>> list_reader,
  );

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIdrisDbReader>,
      ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
      ffi.Pointer<ffi.Uint32>,
    )
  >(symbol: 'IDRISDB_read_to_json')
  external int IDRISDB_read_to_json(
    ffi.Pointer<CIdrisDbReader> reader,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> buffer,
    ffi.Pointer<ffi.Uint32> buffer_size,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIdrisDbReader>)>(
    symbol: 'IDRISDB_read_free',
  )
  external void IDRISDB_read_free(ffi.Pointer<CIdrisDbReader> reader);

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Uint16,
      IDRISDBI64,
      ffi.Pointer<CIDRISDBUpdate>,
      ffi.Pointer<ffi.Bool>,
    )
  >(symbol: 'IDRISDB_update')
  external int IDRISDB_update(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int id,
    ffi.Pointer<CIDRISDBUpdate> update,
    ffi.Pointer<ffi.Bool> updated,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIdrisDbTxn>,
      ffi.Pointer<CIDRISDBQuery>,
      ffi.Uint32,
      ffi.Uint32,
      ffi.Pointer<CIDRISDBUpdate>,
      ffi.Pointer<ffi.Uint32>,
    )
  >(symbol: 'IDRISDB_query_update')
  external int IDRISDB_query_update(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int offset,
    int limit,
    ffi.Pointer<CIDRISDBUpdate> update,
    ffi.Pointer<ffi.Uint32> updated,
  );

  @ffi.Native<ffi.Pointer<CIDRISDBUpdate> Function()>(symbol: 'IDRISDB_update_new')
  external ffi.Pointer<CIDRISDBUpdate> IDRISDB_update_new();

  @ffi.Native<
    ffi.Void Function(
      ffi.Pointer<CIDRISDBUpdate>,
      ffi.Uint16,
      ffi.Pointer<CIDRISDBValue>,
    )
  >(symbol: 'IDRISDB_update_add_value')
  external void IDRISDB_update_add_value(
    ffi.Pointer<CIDRISDBUpdate> update,
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
  );

  @ffi.Native<ffi.Pointer<CIDRISDBValue> Function(ffi.Bool)>(
    symbol: 'IDRISDB_value_bool',
  )
  external ffi.Pointer<CIDRISDBValue> IDRISDB_value_bool(bool value);

  @ffi.Native<ffi.Pointer<CIDRISDBValue> Function(IDRISDBI64)>(
    symbol: 'IDRISDB_value_integer',
  )
  external ffi.Pointer<CIDRISDBValue> IDRISDB_value_integer(int value);

  @ffi.Native<ffi.Pointer<CIDRISDBValue> Function(ffi.Double)>(
    symbol: 'IDRISDB_value_real',
  )
  external ffi.Pointer<CIDRISDBValue> IDRISDB_value_real(double value);

  @ffi.Native<ffi.Pointer<CIDRISDBValue> Function(ffi.Pointer<CString>)>(
    symbol: 'IDRISDB_value_string',
  )
  external ffi.Pointer<CIDRISDBValue> IDRISDB_value_string(
    ffi.Pointer<CString> value,
  );

  @ffi.Native<ffi.Uint8 Function(ffi.Pointer<CIDRISDBValue>)>(
    symbol: 'IDRISDB_value_get_bool',
  )
  external int IDRISDB_value_get_bool(ffi.Pointer<CIDRISDBValue> value);

  @ffi.Native<IDRISDBI64 Function(ffi.Pointer<CIDRISDBValue>)>(
    symbol: 'IDRISDB_value_get_integer',
  )
  external int IDRISDB_value_get_integer(ffi.Pointer<CIDRISDBValue> value);

  @ffi.Native<ffi.Double Function(ffi.Pointer<CIDRISDBValue>)>(
    symbol: 'IDRISDB_value_get_real',
  )
  external double IDRISDB_value_get_real(ffi.Pointer<CIDRISDBValue> value);

  @ffi.Native<
    ffi.Uint32 Function(
      ffi.Pointer<CIDRISDBValue>,
      ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    )
  >(symbol: 'IDRISDB_value_get_string')
  external int IDRISDB_value_get_string(
    ffi.Pointer<CIDRISDBValue> value,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> str,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIDRISDBValue>)>(
    symbol: 'IDRISDB_value_free',
  )
  external void IDRISDB_value_free(ffi.Pointer<CIDRISDBValue> value);

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Uint16,
      DartPort,
      ffi.Pointer<ffi.Pointer<CWatchHandle>>,
    )
  >(symbol: 'IDRISDB_watch_collection')
  external int IDRISDB_watch_collection(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Uint16,
      ffi.Int64,
      DartPort,
      ffi.Pointer<ffi.Pointer<CWatchHandle>>,
    )
  >(symbol: 'IDRISDB_watch_object')
  external int IDRISDB_watch_object(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int id,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Pointer<CIDRISDBQuery>,
      DartPort,
      ffi.Pointer<ffi.Pointer<CWatchHandle>>,
    )
  >(symbol: 'IDRISDB_watch_query')
  external int IDRISDB_watch_query(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIDRISDBQuery> query,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  );

  @ffi.Native<
    ffi.Uint8 Function(
      ffi.Pointer<CIdrisDbInstance>,
      ffi.Uint16,
      DartPort,
      ffi.Pointer<ffi.Pointer<CWatchHandle>>,
    )
  >(symbol: 'IDRISDB_watch_collection_detailed')
  external int IDRISDB_watch_collection_detailed(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CWatchHandle>)>(
    symbol: 'IDRISDB_stop_watching',
  )
  external void IDRISDB_stop_watching(ffi.Pointer<CWatchHandle> handle);

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32)>(
    symbol: 'IDRISDB_write_null',
  )
  external void IDRISDB_write_null(ffi.Pointer<CIdrisDbWriter> writer, int index);

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Bool)
  >(symbol: 'IDRISDB_write_bool')
  external void IDRISDB_write_bool(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    bool value,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Uint8)
  >(symbol: 'IDRISDB_write_byte')
  external void IDRISDB_write_byte(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    int value,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Int32)
  >(symbol: 'IDRISDB_write_int')
  external void IDRISDB_write_int(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    int value,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Float)
  >(symbol: 'IDRISDB_write_float')
  external void IDRISDB_write_float(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    double value,
  );

  @ffi.Native<ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, IDRISDBI64)>(
    symbol: 'IDRISDB_write_long',
  )
  external void IDRISDB_write_long(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    int value,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Double)
  >(symbol: 'IDRISDB_write_double')
  external void IDRISDB_write_double(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    double value,
  );

  @ffi.Native<
    ffi.Void Function(
      ffi.Pointer<CIdrisDbWriter>,
      ffi.Uint32,
      ffi.Pointer<CString>,
    )
  >(symbol: 'IDRISDB_write_string')
  external void IDRISDB_write_string(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<CString> value,
  );

  @ffi.Native<
    ffi.Void Function(
      ffi.Pointer<CIdrisDbWriter>,
      ffi.Uint32,
      ffi.Pointer<CString>,
    )
  >(symbol: 'IDRISDB_write_json')
  external void IDRISDB_write_json(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<CString> value,
  );

  @ffi.Native<
    ffi.Void Function(
      ffi.Pointer<CIdrisDbWriter>,
      ffi.Uint32,
      ffi.Pointer<ffi.Uint8>,
      ffi.Uint32,
    )
  >(symbol: 'IDRISDB_write_byte_list')
  external void IDRISDB_write_byte_list(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<ffi.Uint8> value,
    int length,
  );

  @ffi.Native<
    ffi.Pointer<CIdrisDbWriter> Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32)
  >(symbol: 'IDRISDB_write_object')
  external ffi.Pointer<CIdrisDbWriter> IDRISDB_write_object(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
  >(symbol: 'IDRISDB_write_object_end')
  external void IDRISDB_write_object_end(
    ffi.Pointer<CIdrisDbWriter> writer,
    ffi.Pointer<CIdrisDbWriter> embedded_writer,
  );

  @ffi.Native<
    ffi.Pointer<CIdrisDbWriter> Function(
      ffi.Pointer<CIdrisDbWriter>,
      ffi.Uint32,
      ffi.Uint32,
    )
  >(symbol: 'IDRISDB_write_list')
  external ffi.Pointer<CIdrisDbWriter> IDRISDB_write_list(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    int length,
  );

  @ffi.Native<
    ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
  >(symbol: 'IDRISDB_write_list_end')
  external void IDRISDB_write_list_end(
    ffi.Pointer<CIdrisDbWriter> writer,
    ffi.Pointer<CIdrisDbWriter> list_writer,
  );

  @ffi.Native<ffi.Uint32 Function(ffi.Pointer<CString>)>(
    symbol: 'IDRISDB_web_persistence_start',
  )
  external int IDRISDB_web_persistence_start(ffi.Pointer<CString> directory);

  @ffi.Native<ffi.Uint8 Function(ffi.Uint32)>(
    symbol: 'IDRISDB_web_persistence_poll',
  )
  external int IDRISDB_web_persistence_poll(int handle);

  @ffi.Native<ffi.Uint8 Function()>(symbol: 'IDRISDB_web_persistence_backend')
  external int IDRISDB_web_persistence_backend();
}

final class CIDRISDBCursor extends ffi.Opaque {}

final class CIdrisDbInstance extends ffi.Opaque {}

final class CIDRISDBQuery extends ffi.Opaque {}

final class CIDRISDBQueryBuilder extends ffi.Opaque {}

final class CIdrisDbReader extends ffi.Opaque {}

final class CIdrisDbTxn extends ffi.Opaque {}

final class CIdrisDbWriter extends ffi.Opaque {}

final class CIDRISDBValue extends ffi.Opaque {}

final class CString extends ffi.Opaque {}

typedef IDRISDBI64 = ffi.Int64;

final class CIdrisDbQueryCursor extends ffi.Opaque {}

final class CFilter extends ffi.Opaque {}

final class CIDRISDBUpdate extends ffi.Opaque {}

typedef DartPort = ffi.Int64;

final class CWatchHandle extends ffi.Opaque {}

const int ERROR_PATH = 1;

const int ERROR_WRITE_TXN_REQUIRED = 2;

const int ERROR_VERSION = 3;

const int ERROR_OBJECT_LIMIT_REACHED = 4;

const int ERROR_INSTANCE_MISMATCH = 5;

const int ERROR_ENCRYPTION = 6;

const int ERROR_DB_FULL = 7;

const int AGGREGATION_COUNT = 0;

const int AGGREGATION_IS_EMPTY = 1;

const int AGGREGATION_MIN = 2;

const int AGGREGATION_MAX = 3;

const int AGGREGATION_SUM = 4;

const int AGGREGATION_AVERAGE = 5;
