name: idris_db_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  integration_test:
    sdk: flutter
  intl: ^0.20.2
  idris_db: ^1.0.0
  idris_db_flutter_libs: ^1.0.0
  json_annotation: ^4.9.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  test: any


dev_dependencies:
  build_runner: ^2.13.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  very_good_analysis: ^10.1.0


dependency_overrides:
  idris_db:
    path: ../idris_db
  idris_db_flutter_libs:
    path: ../idris_db_flutter_libs
