// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class IdrisDbCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IdrisDbCoreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IdrisDbCoreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<CString> IDRISDB_string(ffi.Pointer<ffi.Uint16> chars, int length) {
    return _IDRISDB_string(chars, length);
  }

  late final _IDRISDB_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CString> Function(ffi.Pointer<ffi.Uint16>, ffi.Uint32)
        >
      >('IDRISDB_string');
  late final _IDRISDB_string = _IDRISDB_stringPtr
      .asFunction<
        ffi.Pointer<CString> Function(ffi.Pointer<ffi.Uint16>, int)
      >();

  void IDRISDB_string_free(ffi.Pointer<CString> value) {
    return _IDRISDB_string_free(value);
  }

  late final _IDRISDB_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CString>)>>(
        'IDRISDB_string_free',
      );
  late final _IDRISDB_string_free = _IDRISDB_string_freePtr
      .asFunction<void Function(ffi.Pointer<CString>)>();

  void IDRISDB_buffer_free(ffi.Pointer<ffi.Uint8> value, int capacity) {
    return _IDRISDB_buffer_free(value, capacity);
  }

  late final _IDRISDB_buffer_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32)
        >
      >('IDRISDB_buffer_free');
  late final _IDRISDB_buffer_free = _IDRISDB_buffer_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int)>();

  int IDRISDB_get_error(ffi.Pointer<ffi.Pointer<ffi.Uint8>> value) {
    return _IDRISDB_get_error(value);
  }

  late final _IDRISDB_get_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>)
        >
      >('IDRISDB_get_error');
  late final _IDRISDB_get_error = _IDRISDB_get_errorPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>)>();

  ffi.Pointer<CIdrisDbReader> IDRISDB_cursor_next(
    ffi.Pointer<CIDRISDBCursor> cursor,
    int id,
    ffi.Pointer<CIdrisDbReader> old_reader,
  ) {
    return _IDRISDB_cursor_next(cursor, id, old_reader);
  }

  late final _IDRISDB_cursor_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbReader> Function(
            ffi.Pointer<CIDRISDBCursor>,
            IDRISDBI64,
            ffi.Pointer<CIdrisDbReader>,
          )
        >
      >('IDRISDB_cursor_next');
  late final _IDRISDB_cursor_next = _IDRISDB_cursor_nextPtr
      .asFunction<
        ffi.Pointer<CIdrisDbReader> Function(
          ffi.Pointer<CIDRISDBCursor>,
          int,
          ffi.Pointer<CIdrisDbReader>,
        )
      >();

  void IDRISDB_cursor_free(
    ffi.Pointer<CIDRISDBCursor> cursor,
    ffi.Pointer<CIdrisDbReader> reader,
  ) {
    return _IDRISDB_cursor_free(cursor, reader);
  }

  late final _IDRISDB_cursor_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIDRISDBCursor>, ffi.Pointer<CIdrisDbReader>)
        >
      >('IDRISDB_cursor_free');
  late final _IDRISDB_cursor_free = _IDRISDB_cursor_freePtr
      .asFunction<
        void Function(ffi.Pointer<CIDRISDBCursor>, ffi.Pointer<CIdrisDbReader>)
      >();

  ffi.Pointer<CIdrisDbReader> IDRISDB_query_cursor_next(
    ffi.Pointer<CIdrisDbQueryCursor> cursor,
    ffi.Pointer<CIdrisDbReader> old_reader,
  ) {
    return _IDRISDB_query_cursor_next(cursor, old_reader);
  }

  late final _IDRISDB_query_cursor_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbReader> Function(
            ffi.Pointer<CIdrisDbQueryCursor>,
            ffi.Pointer<CIdrisDbReader>,
          )
        >
      >('IDRISDB_query_cursor_next');
  late final _IDRISDB_query_cursor_next = _IDRISDB_query_cursor_nextPtr
      .asFunction<
        ffi.Pointer<CIdrisDbReader> Function(
          ffi.Pointer<CIdrisDbQueryCursor>,
          ffi.Pointer<CIdrisDbReader>,
        )
      >();

  void IDRISDB_query_cursor_free(
    ffi.Pointer<CIdrisDbQueryCursor> cursor,
    ffi.Pointer<CIdrisDbReader> reader,
  ) {
    return _IDRISDB_query_cursor_free(cursor, reader);
  }

  late final _IDRISDB_query_cursor_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIdrisDbQueryCursor>,
            ffi.Pointer<CIdrisDbReader>,
          )
        >
      >('IDRISDB_query_cursor_free');
  late final _IDRISDB_query_cursor_free = _IDRISDB_query_cursor_freePtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbQueryCursor>, ffi.Pointer<CIdrisDbReader>)
      >();

  void IDRISDB_connect_dart_api(ffi.Pointer<ffi.Void> ptr) {
    return _IDRISDB_connect_dart_api(ptr);
  }

  late final _IDRISDB_connect_dart_apiPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'IDRISDB_connect_dart_api',
      );
  late final _IDRISDB_connect_dart_api = _IDRISDB_connect_dart_apiPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<CFilter> IDRISDB_filter_is_null(int property_index) {
    return _IDRISDB_filter_is_null(property_index);
  }

  late final _IDRISDB_filter_is_nullPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CFilter> Function(ffi.Uint16)>>(
        'IDRISDB_filter_is_null',
      );
  late final _IDRISDB_filter_is_null = _IDRISDB_filter_is_nullPtr
      .asFunction<ffi.Pointer<CFilter> Function(int)>(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_equal(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_equalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_equal');
  late final _IDRISDB_filter_equal = _IDRISDB_filter_equalPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_greater(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_greater(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_greaterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_greater');
  late final _IDRISDB_filter_greater = _IDRISDB_filter_greaterPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_greater_or_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_greater_or_equal(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_greater_or_equalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_greater_or_equal');
  late final _IDRISDB_filter_greater_or_equal = _IDRISDB_filter_greater_or_equalPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_less(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_less(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_lessPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_less');
  late final _IDRISDB_filter_less = _IDRISDB_filter_lessPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_less_or_equal(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_less_or_equal(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_less_or_equalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_less_or_equal');
  late final _IDRISDB_filter_less_or_equal = _IDRISDB_filter_less_or_equalPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_between(
    int property_index,
    ffi.Pointer<CIDRISDBValue> lower,
    ffi.Pointer<CIDRISDBValue> upper,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_between(property_index, lower, upper, case_sensitive);
  }

  late final _IDRISDB_filter_betweenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_between');
  late final _IDRISDB_filter_between = _IDRISDB_filter_betweenPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(
          int,
          ffi.Pointer<CIDRISDBValue>,
          ffi.Pointer<CIDRISDBValue>,
          bool,
        )
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_string_starts_with(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_string_starts_with(
      property_index,
      value,
      case_sensitive,
    );
  }

  late final _IDRISDB_filter_string_starts_withPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_string_starts_with');
  late final _IDRISDB_filter_string_starts_with =
      _IDRISDB_filter_string_starts_withPtr.asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_string_ends_with(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_string_ends_with(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_string_ends_withPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_string_ends_with');
  late final _IDRISDB_filter_string_ends_with = _IDRISDB_filter_string_ends_withPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_string_contains(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_string_contains(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_string_containsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_string_contains');
  late final _IDRISDB_filter_string_contains = _IDRISDB_filter_string_containsPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_string_matches(
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
    bool case_sensitive,
  ) {
    return _IDRISDB_filter_string_matches(property_index, value, case_sensitive);
  }

  late final _IDRISDB_filter_string_matchesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
            ffi.Bool,
          )
        >
      >('IDRISDB_filter_string_matches');
  late final _IDRISDB_filter_string_matches = _IDRISDB_filter_string_matchesPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(int, ffi.Pointer<CIDRISDBValue>, bool)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_nested(
    int property_index,
    ffi.Pointer<CFilter> filter,
  ) {
    return _IDRISDB_filter_nested(property_index, filter);
  }

  late final _IDRISDB_filter_nestedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(ffi.Uint16, ffi.Pointer<CFilter>)
        >
      >('IDRISDB_filter_nested');
  late final _IDRISDB_filter_nested = _IDRISDB_filter_nestedPtr
      .asFunction<ffi.Pointer<CFilter> Function(int, ffi.Pointer<CFilter>)>(
        isLeaf: true,
      );

  ffi.Pointer<CFilter> IDRISDB_filter_and(
    ffi.Pointer<ffi.Pointer<CFilter>> filters,
    int lenght,
  ) {
    return _IDRISDB_filter_and(filters, lenght);
  }

  late final _IDRISDB_filter_andPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Pointer<ffi.Pointer<CFilter>>,
            ffi.Uint32,
          )
        >
      >('IDRISDB_filter_and');
  late final _IDRISDB_filter_and = _IDRISDB_filter_andPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(ffi.Pointer<ffi.Pointer<CFilter>>, int)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_or(
    ffi.Pointer<ffi.Pointer<CFilter>> filters,
    int lenght,
  ) {
    return _IDRISDB_filter_or(filters, lenght);
  }

  late final _IDRISDB_filter_orPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CFilter> Function(
            ffi.Pointer<ffi.Pointer<CFilter>>,
            ffi.Uint32,
          )
        >
      >('IDRISDB_filter_or');
  late final _IDRISDB_filter_or = _IDRISDB_filter_orPtr
      .asFunction<
        ffi.Pointer<CFilter> Function(ffi.Pointer<ffi.Pointer<CFilter>>, int)
      >(isLeaf: true);

  ffi.Pointer<CFilter> IDRISDB_filter_not(ffi.Pointer<CFilter> filter) {
    return _IDRISDB_filter_not(filter);
  }

  late final _IDRISDB_filter_notPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<CFilter> Function(ffi.Pointer<CFilter>)>
      >('IDRISDB_filter_not');
  late final _IDRISDB_filter_not = _IDRISDB_filter_notPtr
      .asFunction<ffi.Pointer<CFilter> Function(ffi.Pointer<CFilter>)>(
        isLeaf: true,
      );

  int IDRISDB_insert(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int count,
    ffi.Pointer<ffi.Pointer<CIdrisDbWriter>> insert,
  ) {
    return _IDRISDB_insert(IdrisDb, txn, collection_index, count, insert);
  }

  late final _IDRISDB_insertPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            ffi.Uint32,
            ffi.Pointer<ffi.Pointer<CIdrisDbWriter>>,
          )
        >
      >('IDRISDB_insert');
  late final _IDRISDB_insert = _IDRISDB_insertPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<CIdrisDbWriter>>,
        )
      >();

  int IDRISDB_insert_save(ffi.Pointer<CIdrisDbWriter> insert, int id) {
    return _IDRISDB_insert_save(insert, id);
  }

  late final _IDRISDB_insert_savePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbWriter>, IDRISDBI64)
        >
      >('IDRISDB_insert_save');
  late final _IDRISDB_insert_save = _IDRISDB_insert_savePtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbWriter>, int)>();

  int IDRISDB_insert_finish(
    ffi.Pointer<CIdrisDbWriter> insert,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
  ) {
    return _IDRISDB_insert_finish(insert, txn);
  }

  late final _IDRISDB_insert_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
          )
        >
      >('IDRISDB_insert_finish');
  late final _IDRISDB_insert_finish = _IDRISDB_insert_finishPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbWriter>,
          ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
        )
      >();

  void IDRISDB_insert_abort(ffi.Pointer<CIdrisDbWriter> insert) {
    return _IDRISDB_insert_abort(insert);
  }

  late final _IDRISDB_insert_abortPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CIdrisDbWriter>)>>(
        'IDRISDB_insert_abort',
      );
  late final _IDRISDB_insert_abort = _IDRISDB_insert_abortPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>)>();

  ffi.Pointer<ffi.Char> IDRISDB_version() {
    return _IDRISDB_version();
  }

  late final _IDRISDB_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'IDRISDB_version',
      );
  late final _IDRISDB_version = _IDRISDB_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<CIdrisDbInstance> IDRISDB_get_instance(int instance_id, bool sqlite) {
    return _IDRISDB_get_instance(instance_id, sqlite);
  }

  late final _IDRISDB_get_instancePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbInstance> Function(ffi.Uint32, ffi.Bool)
        >
      >('IDRISDB_get_instance');
  late final _IDRISDB_get_instance = _IDRISDB_get_instancePtr
      .asFunction<ffi.Pointer<CIdrisDbInstance> Function(int, bool)>();

  int IDRISDB_open_instance(
    ffi.Pointer<ffi.Pointer<CIdrisDbInstance>> IdrisDb,
    int instance_id,
    ffi.Pointer<CString> name,
    ffi.Pointer<CString> path,
    bool sqlite,
    ffi.Pointer<CString> schema_json,
    int max_size_mib,
    ffi.Pointer<CString> encryption_key,
    int compact_min_file_size,
    int compact_min_bytes,
    double compact_min_ratio,
  ) {
    return _IDRISDB_open_instance(
      IdrisDb,
      instance_id,
      name,
      path,
      sqlite,
      schema_json,
      max_size_mib,
      encryption_key,
      compact_min_file_size,
      compact_min_bytes,
      compact_min_ratio,
    );
  }

  late final _IDRISDB_open_instancePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<ffi.Pointer<CIdrisDbInstance>>,
            ffi.Uint32,
            ffi.Pointer<CString>,
            ffi.Pointer<CString>,
            ffi.Bool,
            ffi.Pointer<CString>,
            ffi.Uint32,
            ffi.Pointer<CString>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Float,
          )
        >
      >('IDRISDB_open_instance');
  late final _IDRISDB_open_instance = _IDRISDB_open_instancePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<CIdrisDbInstance>>,
          int,
          ffi.Pointer<CString>,
          ffi.Pointer<CString>,
          bool,
          ffi.Pointer<CString>,
          int,
          ffi.Pointer<CString>,
          int,
          int,
          double,
        )
      >();

  int IDRISDB_get_name(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> name,
  ) {
    return _IDRISDB_get_name(IdrisDb, name);
  }

  late final _IDRISDB_get_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('IDRISDB_get_name');
  late final _IDRISDB_get_name = _IDRISDB_get_namePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int IDRISDB_get_dir(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> dir,
  ) {
    return _IDRISDB_get_dir(IdrisDb, dir);
  }

  late final _IDRISDB_get_dirPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('IDRISDB_get_dir');
  late final _IDRISDB_get_dir = _IDRISDB_get_dirPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int IDRISDB_txn_begin(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
    bool write,
  ) {
    return _IDRISDB_txn_begin(IdrisDb, txn, write);
  }

  late final _IDRISDB_txn_beginPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
            ffi.Bool,
          )
        >
      >('IDRISDB_txn_begin');
  late final _IDRISDB_txn_begin = _IDRISDB_txn_beginPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
          bool,
        )
      >();

  int IDRISDB_txn_commit(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
  ) {
    return _IDRISDB_txn_commit(IdrisDb, txn);
  }

  late final _IDRISDB_txn_commitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
        >
      >('IDRISDB_txn_commit');
  late final _IDRISDB_txn_commit = _IDRISDB_txn_commitPtr
      .asFunction<
        int Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
      >();

  void IDRISDB_txn_abort(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
  ) {
    return _IDRISDB_txn_abort(IdrisDb, txn);
  }

  late final _IDRISDB_txn_abortPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
        >
      >('IDRISDB_txn_abort');
  late final _IDRISDB_txn_abort = _IDRISDB_txn_abortPtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
      >();

  int IDRISDB_auto_increment(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
  ) {
    return _IDRISDB_auto_increment(IdrisDb, collection_index);
  }

  late final _IDRISDB_auto_incrementPtr =
      _lookup<
        ffi.NativeFunction<
          IDRISDBI64 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Uint16)
        >
      >('IDRISDB_auto_increment');
  late final _IDRISDB_auto_increment = _IDRISDB_auto_incrementPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbInstance>, int)>();

  int IDRISDB_cursor(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBCursor>> cursor,
  ) {
    return _IDRISDB_cursor(IdrisDb, txn, collection_index, cursor);
  }

  late final _IDRISDB_cursorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            ffi.Pointer<ffi.Pointer<CIDRISDBCursor>>,
          )
        >
      >('IDRISDB_cursor');
  late final _IDRISDB_cursor = _IDRISDB_cursorPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          ffi.Pointer<ffi.Pointer<CIDRISDBCursor>>,
        )
      >();

  int IDRISDB_delete(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int id,
    ffi.Pointer<ffi.Bool> deleted,
  ) {
    return _IDRISDB_delete(IdrisDb, txn, collection_index, id, deleted);
  }

  late final _IDRISDB_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            IDRISDBI64,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('IDRISDB_delete');
  late final _IDRISDB_delete = _IDRISDB_deletePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          int,
          ffi.Pointer<ffi.Bool>,
        )
      >();

  int IDRISDB_count(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _IDRISDB_count(IdrisDb, txn, collection_index, count);
  }

  late final _IDRISDB_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IDRISDB_count');
  late final _IDRISDB_count = _IDRISDB_countPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  int IDRISDB_clear(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
  ) {
    return _IDRISDB_clear(IdrisDb, txn, collection_index);
  }

  late final _IDRISDB_clearPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
          )
        >
      >('IDRISDB_clear');
  late final _IDRISDB_clear = _IDRISDB_clearPtr
      .asFunction<
        int Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>, int)
      >();

  int IDRISDB_get_size(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    bool include_indexes,
  ) {
    return _IDRISDB_get_size(IdrisDb, txn, collection_index, include_indexes);
  }

  late final _IDRISDB_get_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            ffi.Bool,
          )
        >
      >('IDRISDB_get_size');
  late final _IDRISDB_get_size = _IDRISDB_get_sizePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          bool,
        )
      >();

  int IDRISDB_import_json(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<ffi.Pointer<CIdrisDbTxn>> txn,
    int collection_index,
    ffi.Pointer<CString> json,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _IDRISDB_import_json(IdrisDb, txn, collection_index, json, count);
  }

  late final _IDRISDB_import_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
            ffi.Uint16,
            ffi.Pointer<CString>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IDRISDB_import_json');
  late final _IDRISDB_import_json = _IDRISDB_import_jsonPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<ffi.Pointer<CIdrisDbTxn>>,
          int,
          ffi.Pointer<CString>,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  int IDRISDB_copy(ffi.Pointer<CIdrisDbInstance> IdrisDb, ffi.Pointer<CString> path) {
    return _IDRISDB_copy(IdrisDb, path);
  }

  late final _IDRISDB_copyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CString>)
        >
      >('IDRISDB_copy');
  late final _IDRISDB_copy = _IDRISDB_copyPtr
      .asFunction<
        int Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CString>)
      >();

  int IDRISDB_verify(ffi.Pointer<CIdrisDbInstance> IdrisDb, ffi.Pointer<CIdrisDbTxn> txn) {
    return _IDRISDB_verify(IdrisDb, txn);
  }

  late final _IDRISDB_verifyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
        >
      >('IDRISDB_verify');
  late final _IDRISDB_verify = _IDRISDB_verifyPtr
      .asFunction<
        int Function(ffi.Pointer<CIdrisDbInstance>, ffi.Pointer<CIdrisDbTxn>)
      >();

  int IDRISDB_close(ffi.Pointer<CIdrisDbInstance> IdrisDb, bool delete_) {
    return _IDRISDB_close(IdrisDb, delete_);
  }

  late final _IDRISDB_closePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbInstance>, ffi.Bool)
        >
      >('IDRISDB_close');
  late final _IDRISDB_close = _IDRISDB_closePtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbInstance>, bool)>();

  int IDRISDB_delete_database(
    ffi.Pointer<CString> name,
    ffi.Pointer<CString> path,
    bool sqlite,
  ) {
    return _IDRISDB_delete_database(name, path, sqlite);
  }

  late final _IDRISDB_delete_databasePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CString>,
            ffi.Pointer<CString>,
            ffi.Bool,
          )
        >
      >('IDRISDB_delete_database');
  late final _IDRISDB_delete_database = _IDRISDB_delete_databasePtr
      .asFunction<
        int Function(ffi.Pointer<CString>, ffi.Pointer<CString>, bool)
      >();

  int IDRISDB_query_new(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBQueryBuilder>> query_builder,
  ) {
    return _IDRISDB_query_new(IdrisDb, collection_index, query_builder);
  }

  late final _IDRISDB_query_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Uint16,
            ffi.Pointer<ffi.Pointer<CIDRISDBQueryBuilder>>,
          )
        >
      >('IDRISDB_query_new');
  late final _IDRISDB_query_new = _IDRISDB_query_newPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          int,
          ffi.Pointer<ffi.Pointer<CIDRISDBQueryBuilder>>,
        )
      >();

  void IDRISDB_query_set_filter(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    ffi.Pointer<CFilter> filter,
  ) {
    return _IDRISDB_query_set_filter(builder, filter);
  }

  late final _IDRISDB_query_set_filterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIDRISDBQueryBuilder>,
            ffi.Pointer<CFilter>,
          )
        >
      >('IDRISDB_query_set_filter');
  late final _IDRISDB_query_set_filter = _IDRISDB_query_set_filterPtr
      .asFunction<
        void Function(ffi.Pointer<CIDRISDBQueryBuilder>, ffi.Pointer<CFilter>)
      >();

  void IDRISDB_query_add_sort(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    int property_index,
    bool ascending,
    bool case_sensitive,
  ) {
    return _IDRISDB_query_add_sort(
      builder,
      property_index,
      ascending,
      case_sensitive,
    );
  }

  late final _IDRISDB_query_add_sortPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIDRISDBQueryBuilder>,
            ffi.Uint16,
            ffi.Bool,
            ffi.Bool,
          )
        >
      >('IDRISDB_query_add_sort');
  late final _IDRISDB_query_add_sort = _IDRISDB_query_add_sortPtr
      .asFunction<
        void Function(ffi.Pointer<CIDRISDBQueryBuilder>, int, bool, bool)
      >();

  void IDRISDB_query_add_distinct(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
    int property_index,
    bool case_sensitive,
  ) {
    return _IDRISDB_query_add_distinct(builder, property_index, case_sensitive);
  }

  late final _IDRISDB_query_add_distinctPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIDRISDBQueryBuilder>,
            ffi.Uint16,
            ffi.Bool,
          )
        >
      >('IDRISDB_query_add_distinct');
  late final _IDRISDB_query_add_distinct = _IDRISDB_query_add_distinctPtr
      .asFunction<void Function(ffi.Pointer<CIDRISDBQueryBuilder>, int, bool)>();

  ffi.Pointer<CIDRISDBQuery> IDRISDB_query_build(
    ffi.Pointer<CIDRISDBQueryBuilder> builder,
  ) {
    return _IDRISDB_query_build(builder);
  }

  late final _IDRISDB_query_buildPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIDRISDBQuery> Function(ffi.Pointer<CIDRISDBQueryBuilder>)
        >
      >('IDRISDB_query_build');
  late final _IDRISDB_query_build = _IDRISDB_query_buildPtr
      .asFunction<
        ffi.Pointer<CIDRISDBQuery> Function(ffi.Pointer<CIDRISDBQueryBuilder>)
      >();

  int IDRISDB_query_cursor(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    ffi.Pointer<ffi.Pointer<CIdrisDbQueryCursor>> cursor,
    int offset,
    int limit,
  ) {
    return _IDRISDB_query_cursor(IdrisDb, txn, query, cursor, offset, limit);
  }

  late final _IDRISDB_query_cursorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Pointer<CIDRISDBQuery>,
            ffi.Pointer<ffi.Pointer<CIdrisDbQueryCursor>>,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('IDRISDB_query_cursor');
  late final _IDRISDB_query_cursor = _IDRISDB_query_cursorPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          ffi.Pointer<CIDRISDBQuery>,
          ffi.Pointer<ffi.Pointer<CIdrisDbQueryCursor>>,
          int,
          int,
        )
      >();

  int IDRISDB_query_aggregate(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int aggregation,
    int property_index,
    ffi.Pointer<ffi.Pointer<CIDRISDBValue>> value,
  ) {
    return _IDRISDB_query_aggregate(
      IdrisDb,
      txn,
      query,
      aggregation,
      property_index,
      value,
    );
  }

  late final _IDRISDB_query_aggregatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Pointer<CIDRISDBQuery>,
            ffi.Uint8,
            ffi.Uint16,
            ffi.Pointer<ffi.Pointer<CIDRISDBValue>>,
          )
        >
      >('IDRISDB_query_aggregate');
  late final _IDRISDB_query_aggregate = _IDRISDB_query_aggregatePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          ffi.Pointer<CIDRISDBQuery>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<CIDRISDBValue>>,
        )
      >();

  int IDRISDB_query_delete(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int offset,
    int limit,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _IDRISDB_query_delete(IdrisDb, txn, query, offset, limit, count);
  }

  late final _IDRISDB_query_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Pointer<CIDRISDBQuery>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IDRISDB_query_delete');
  late final _IDRISDB_query_delete = _IDRISDB_query_deletePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          ffi.Pointer<CIDRISDBQuery>,
          int,
          int,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  void IDRISDB_query_free(ffi.Pointer<CIDRISDBQuery> query) {
    return _IDRISDB_query_free(query);
  }

  late final _IDRISDB_query_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CIDRISDBQuery>)>>(
        'IDRISDB_query_free',
      );
  late final _IDRISDB_query_free = _IDRISDB_query_freePtr
      .asFunction<void Function(ffi.Pointer<CIDRISDBQuery>)>();

  int IDRISDB_read_id(ffi.Pointer<CIdrisDbReader> reader) {
    return _IDRISDB_read_id(reader);
  }

  late final _IDRISDB_read_idPtr =
      _lookup<ffi.NativeFunction<IDRISDBI64 Function(ffi.Pointer<CIdrisDbReader>)>>(
        'IDRISDB_read_id',
      );
  late final _IDRISDB_read_id = _IDRISDB_read_idPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>)>(isLeaf: true);

  int IDRISDB_read_null(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_null(reader, index);
  }

  late final _IDRISDB_read_nullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_null');
  late final _IDRISDB_read_null = _IDRISDB_read_nullPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  int IDRISDB_read_bool(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_bool(reader, index);
  }

  late final _IDRISDB_read_boolPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_bool');
  late final _IDRISDB_read_bool = _IDRISDB_read_boolPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  int IDRISDB_read_byte(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_byte(reader, index);
  }

  late final _IDRISDB_read_bytePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_byte');
  late final _IDRISDB_read_byte = _IDRISDB_read_bytePtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  int IDRISDB_read_int(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_int(reader, index);
  }

  late final _IDRISDB_read_intPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_int');
  late final _IDRISDB_read_int = _IDRISDB_read_intPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  double IDRISDB_read_float(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_float(reader, index);
  }

  late final _IDRISDB_read_floatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Float Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_float');
  late final _IDRISDB_read_float = _IDRISDB_read_floatPtr
      .asFunction<double Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  int IDRISDB_read_long(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_long(reader, index);
  }

  late final _IDRISDB_read_longPtr =
      _lookup<
        ffi.NativeFunction<
          IDRISDBI64 Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_long');
  late final _IDRISDB_read_long = _IDRISDB_read_longPtr
      .asFunction<int Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  double IDRISDB_read_double(ffi.Pointer<CIdrisDbReader> reader, int index) {
    return _IDRISDB_read_double(reader, index);
  }

  late final _IDRISDB_read_doublePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<CIdrisDbReader>, ffi.Uint32)
        >
      >('IDRISDB_read_double');
  late final _IDRISDB_read_double = _IDRISDB_read_doublePtr
      .asFunction<double Function(ffi.Pointer<CIdrisDbReader>, int)>(isLeaf: true);

  int IDRISDB_read_string(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> value,
    ffi.Pointer<ffi.Bool> is_ascii,
  ) {
    return _IDRISDB_read_string(reader, index, value, is_ascii);
  }

  late final _IDRISDB_read_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbReader>,
            ffi.Uint32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('IDRISDB_read_string');
  late final _IDRISDB_read_string = _IDRISDB_read_stringPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbReader>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Bool>,
        )
      >(isLeaf: true);

  ffi.Pointer<CIdrisDbReader> IDRISDB_read_object(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
  ) {
    return _IDRISDB_read_object(reader, index);
  }

  late final _IDRISDB_read_objectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbReader> Function(
            ffi.Pointer<CIdrisDbReader>,
            ffi.Uint32,
          )
        >
      >('IDRISDB_read_object');
  late final _IDRISDB_read_object = _IDRISDB_read_objectPtr
      .asFunction<
        ffi.Pointer<CIdrisDbReader> Function(ffi.Pointer<CIdrisDbReader>, int)
      >(isLeaf: true);

  int IDRISDB_read_list(
    ffi.Pointer<CIdrisDbReader> reader,
    int index,
    ffi.Pointer<ffi.Pointer<CIdrisDbReader>> list_reader,
  ) {
    return _IDRISDB_read_list(reader, index, list_reader);
  }

  late final _IDRISDB_read_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbReader>,
            ffi.Uint32,
            ffi.Pointer<ffi.Pointer<CIdrisDbReader>>,
          )
        >
      >('IDRISDB_read_list');
  late final _IDRISDB_read_list = _IDRISDB_read_listPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbReader>,
          int,
          ffi.Pointer<ffi.Pointer<CIdrisDbReader>>,
        )
      >(isLeaf: true);

  int IDRISDB_read_to_json(
    ffi.Pointer<CIdrisDbReader> reader,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> buffer,
    ffi.Pointer<ffi.Uint32> buffer_size,
  ) {
    return _IDRISDB_read_to_json(reader, buffer, buffer_size);
  }

  late final _IDRISDB_read_to_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIdrisDbReader>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IDRISDB_read_to_json');
  late final _IDRISDB_read_to_json = _IDRISDB_read_to_jsonPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbReader>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Uint32>,
        )
      >(isLeaf: true);

  void IDRISDB_read_free(ffi.Pointer<CIdrisDbReader> reader) {
    return _IDRISDB_read_free(reader);
  }

  late final _IDRISDB_read_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CIdrisDbReader>)>>(
        'IDRISDB_read_free',
      );
  late final _IDRISDB_read_free = _IDRISDB_read_freePtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbReader>)>(isLeaf: true);

  int IDRISDB_update(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    int collection_index,
    int id,
    ffi.Pointer<CIDRISDBUpdate> update,
    ffi.Pointer<ffi.Bool> updated,
  ) {
    return _IDRISDB_update(IdrisDb, txn, collection_index, id, update, updated);
  }

  late final _IDRISDB_updatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Uint16,
            IDRISDBI64,
            ffi.Pointer<CIDRISDBUpdate>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('IDRISDB_update');
  late final _IDRISDB_update = _IDRISDB_updatePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          int,
          int,
          ffi.Pointer<CIDRISDBUpdate>,
          ffi.Pointer<ffi.Bool>,
        )
      >();

  int IDRISDB_query_update(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIdrisDbTxn> txn,
    ffi.Pointer<CIDRISDBQuery> query,
    int offset,
    int limit,
    ffi.Pointer<CIDRISDBUpdate> update,
    ffi.Pointer<ffi.Uint32> updated,
  ) {
    return _IDRISDB_query_update(IdrisDb, txn, query, offset, limit, update, updated);
  }

  late final _IDRISDB_query_updatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIdrisDbTxn>,
            ffi.Pointer<CIDRISDBQuery>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<CIDRISDBUpdate>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IDRISDB_query_update');
  late final _IDRISDB_query_update = _IDRISDB_query_updatePtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIdrisDbTxn>,
          ffi.Pointer<CIDRISDBQuery>,
          int,
          int,
          ffi.Pointer<CIDRISDBUpdate>,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  ffi.Pointer<CIDRISDBUpdate> IDRISDB_update_new() {
    return _IDRISDB_update_new();
  }

  late final _IDRISDB_update_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CIDRISDBUpdate> Function()>>(
        'IDRISDB_update_new',
      );
  late final _IDRISDB_update_new = _IDRISDB_update_newPtr
      .asFunction<ffi.Pointer<CIDRISDBUpdate> Function()>();

  void IDRISDB_update_add_value(
    ffi.Pointer<CIDRISDBUpdate> update,
    int property_index,
    ffi.Pointer<CIDRISDBValue> value,
  ) {
    return _IDRISDB_update_add_value(update, property_index, value);
  }

  late final _IDRISDB_update_add_valuePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIDRISDBUpdate>,
            ffi.Uint16,
            ffi.Pointer<CIDRISDBValue>,
          )
        >
      >('IDRISDB_update_add_value');
  late final _IDRISDB_update_add_value = _IDRISDB_update_add_valuePtr
      .asFunction<
        void Function(ffi.Pointer<CIDRISDBUpdate>, int, ffi.Pointer<CIDRISDBValue>)
      >();

  ffi.Pointer<CIDRISDBValue> IDRISDB_value_bool(bool value) {
    return _IDRISDB_value_bool(value);
  }

  late final _IDRISDB_value_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CIDRISDBValue> Function(ffi.Bool)>>(
        'IDRISDB_value_bool',
      );
  late final _IDRISDB_value_bool = _IDRISDB_value_boolPtr
      .asFunction<ffi.Pointer<CIDRISDBValue> Function(bool)>(isLeaf: true);

  ffi.Pointer<CIDRISDBValue> IDRISDB_value_integer(int value) {
    return _IDRISDB_value_integer(value);
  }

  late final _IDRISDB_value_integerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CIDRISDBValue> Function(IDRISDBI64)>>(
        'IDRISDB_value_integer',
      );
  late final _IDRISDB_value_integer = _IDRISDB_value_integerPtr
      .asFunction<ffi.Pointer<CIDRISDBValue> Function(int)>(isLeaf: true);

  ffi.Pointer<CIDRISDBValue> IDRISDB_value_real(double value) {
    return _IDRISDB_value_real(value);
  }

  late final _IDRISDB_value_realPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CIDRISDBValue> Function(ffi.Double)>>(
        'IDRISDB_value_real',
      );
  late final _IDRISDB_value_real = _IDRISDB_value_realPtr
      .asFunction<ffi.Pointer<CIDRISDBValue> Function(double)>(isLeaf: true);

  ffi.Pointer<CIDRISDBValue> IDRISDB_value_string(ffi.Pointer<CString> value) {
    return _IDRISDB_value_string(value);
  }

  late final _IDRISDB_value_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIDRISDBValue> Function(ffi.Pointer<CString>)
        >
      >('IDRISDB_value_string');
  late final _IDRISDB_value_string = _IDRISDB_value_stringPtr
      .asFunction<ffi.Pointer<CIDRISDBValue> Function(ffi.Pointer<CString>)>(
        isLeaf: true,
      );

  int IDRISDB_value_get_bool(ffi.Pointer<CIDRISDBValue> value) {
    return _IDRISDB_value_get_bool(value);
  }

  late final _IDRISDB_value_get_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Uint8 Function(ffi.Pointer<CIDRISDBValue>)>>(
        'IDRISDB_value_get_bool',
      );
  late final _IDRISDB_value_get_bool = _IDRISDB_value_get_boolPtr
      .asFunction<int Function(ffi.Pointer<CIDRISDBValue>)>(isLeaf: true);

  int IDRISDB_value_get_integer(ffi.Pointer<CIDRISDBValue> value) {
    return _IDRISDB_value_get_integer(value);
  }

  late final _IDRISDB_value_get_integerPtr =
      _lookup<ffi.NativeFunction<IDRISDBI64 Function(ffi.Pointer<CIDRISDBValue>)>>(
        'IDRISDB_value_get_integer',
      );
  late final _IDRISDB_value_get_integer = _IDRISDB_value_get_integerPtr
      .asFunction<int Function(ffi.Pointer<CIDRISDBValue>)>(isLeaf: true);

  double IDRISDB_value_get_real(ffi.Pointer<CIDRISDBValue> value) {
    return _IDRISDB_value_get_real(value);
  }

  late final _IDRISDB_value_get_realPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<CIDRISDBValue>)>>(
        'IDRISDB_value_get_real',
      );
  late final _IDRISDB_value_get_real = _IDRISDB_value_get_realPtr
      .asFunction<double Function(ffi.Pointer<CIDRISDBValue>)>(isLeaf: true);

  int IDRISDB_value_get_string(
    ffi.Pointer<CIDRISDBValue> value,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> str,
  ) {
    return _IDRISDB_value_get_string(value, str);
  }

  late final _IDRISDB_value_get_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<CIDRISDBValue>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('IDRISDB_value_get_string');
  late final _IDRISDB_value_get_string = _IDRISDB_value_get_stringPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIDRISDBValue>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >(isLeaf: true);

  void IDRISDB_value_free(ffi.Pointer<CIDRISDBValue> value) {
    return _IDRISDB_value_free(value);
  }

  late final _IDRISDB_value_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CIDRISDBValue>)>>(
        'IDRISDB_value_free',
      );
  late final _IDRISDB_value_free = _IDRISDB_value_freePtr
      .asFunction<void Function(ffi.Pointer<CIDRISDBValue>)>(isLeaf: true);

  int IDRISDB_watch_collection(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  ) {
    return _IDRISDB_watch_collection(IdrisDb, collection_index, port, handle);
  }

  late final _IDRISDB_watch_collectionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Uint16,
            DartPort,
            ffi.Pointer<ffi.Pointer<CWatchHandle>>,
          )
        >
      >('IDRISDB_watch_collection');
  late final _IDRISDB_watch_collection = _IDRISDB_watch_collectionPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<CWatchHandle>>,
        )
      >();

  int IDRISDB_watch_object(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int id,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  ) {
    return _IDRISDB_watch_object(IdrisDb, collection_index, id, port, handle);
  }

  late final _IDRISDB_watch_objectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Uint16,
            ffi.Int64,
            DartPort,
            ffi.Pointer<ffi.Pointer<CWatchHandle>>,
          )
        >
      >('IDRISDB_watch_object');
  late final _IDRISDB_watch_object = _IDRISDB_watch_objectPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Pointer<CWatchHandle>>,
        )
      >();

  int IDRISDB_watch_query(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    ffi.Pointer<CIDRISDBQuery> query,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  ) {
    return _IDRISDB_watch_query(IdrisDb, query, port, handle);
  }

  late final _IDRISDB_watch_queryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Pointer<CIDRISDBQuery>,
            DartPort,
            ffi.Pointer<ffi.Pointer<CWatchHandle>>,
          )
        >
      >('IDRISDB_watch_query');
  late final _IDRISDB_watch_query = _IDRISDB_watch_queryPtr
      .asFunction<
        int Function(
          ffi.Pointer<CIdrisDbInstance>,
          ffi.Pointer<CIDRISDBQuery>,
          int,
          ffi.Pointer<ffi.Pointer<CWatchHandle>>,
        )
      >();

  int IDRISDB_watch_collection_detailed(
    ffi.Pointer<CIdrisDbInstance> IdrisDb,
    int collection_index,
    int port,
    ffi.Pointer<ffi.Pointer<CWatchHandle>> handle,
  ) {
    return _IDRISDB_watch_collection_detailed(
      IdrisDb,
      collection_index,
      port,
      handle,
    );
  }

  late final _IDRISDB_watch_collection_detailedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            ffi.Pointer<CIdrisDbInstance>,
            ffi.Uint16,
            DartPort,
            ffi.Pointer<ffi.Pointer<CWatchHandle>>,
          )
        >
      >('IDRISDB_watch_collection_detailed');
  late final _IDRISDB_watch_collection_detailed =
      _IDRISDB_watch_collection_detailedPtr
          .asFunction<
            int Function(
              ffi.Pointer<CIdrisDbInstance>,
              int,
              int,
              ffi.Pointer<ffi.Pointer<CWatchHandle>>,
            )
          >();

  void IDRISDB_stop_watching(ffi.Pointer<CWatchHandle> handle) {
    return _IDRISDB_stop_watching(handle);
  }

  late final _IDRISDB_stop_watchingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CWatchHandle>)>>(
        'IDRISDB_stop_watching',
      );
  late final _IDRISDB_stop_watching = _IDRISDB_stop_watchingPtr
      .asFunction<void Function(ffi.Pointer<CWatchHandle>)>();

  void IDRISDB_write_null(ffi.Pointer<CIdrisDbWriter> writer, int index) {
    return _IDRISDB_write_null(writer, index);
  }

  late final _IDRISDB_write_nullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32)
        >
      >('IDRISDB_write_null');
  late final _IDRISDB_write_null = _IDRISDB_write_nullPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int)>(isLeaf: true);

  void IDRISDB_write_bool(ffi.Pointer<CIdrisDbWriter> writer, int index, bool value) {
    return _IDRISDB_write_bool(writer, index, value);
  }

  late final _IDRISDB_write_boolPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Bool)
        >
      >('IDRISDB_write_bool');
  late final _IDRISDB_write_bool = _IDRISDB_write_boolPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, bool)>(
        isLeaf: true,
      );

  void IDRISDB_write_byte(ffi.Pointer<CIdrisDbWriter> writer, int index, int value) {
    return _IDRISDB_write_byte(writer, index, value);
  }

  late final _IDRISDB_write_bytePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Uint8)
        >
      >('IDRISDB_write_byte');
  late final _IDRISDB_write_byte = _IDRISDB_write_bytePtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, int)>(
        isLeaf: true,
      );

  void IDRISDB_write_int(ffi.Pointer<CIdrisDbWriter> writer, int index, int value) {
    return _IDRISDB_write_int(writer, index, value);
  }

  late final _IDRISDB_write_intPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Int32)
        >
      >('IDRISDB_write_int');
  late final _IDRISDB_write_int = _IDRISDB_write_intPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, int)>(
        isLeaf: true,
      );

  void IDRISDB_write_float(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    double value,
  ) {
    return _IDRISDB_write_float(writer, index, value);
  }

  late final _IDRISDB_write_floatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Float)
        >
      >('IDRISDB_write_float');
  late final _IDRISDB_write_float = _IDRISDB_write_floatPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, double)>(
        isLeaf: true,
      );

  void IDRISDB_write_long(ffi.Pointer<CIdrisDbWriter> writer, int index, int value) {
    return _IDRISDB_write_long(writer, index, value);
  }

  late final _IDRISDB_write_longPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, IDRISDBI64)
        >
      >('IDRISDB_write_long');
  late final _IDRISDB_write_long = _IDRISDB_write_longPtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, int)>(
        isLeaf: true,
      );

  void IDRISDB_write_double(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    double value,
  ) {
    return _IDRISDB_write_double(writer, index, value);
  }

  late final _IDRISDB_write_doublePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Uint32, ffi.Double)
        >
      >('IDRISDB_write_double');
  late final _IDRISDB_write_double = _IDRISDB_write_doublePtr
      .asFunction<void Function(ffi.Pointer<CIdrisDbWriter>, int, double)>(
        isLeaf: true,
      );

  void IDRISDB_write_string(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<CString> value,
  ) {
    return _IDRISDB_write_string(writer, index, value);
  }

  late final _IDRISDB_write_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Uint32,
            ffi.Pointer<CString>,
          )
        >
      >('IDRISDB_write_string');
  late final _IDRISDB_write_string = _IDRISDB_write_stringPtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbWriter>, int, ffi.Pointer<CString>)
      >(isLeaf: true);

  void IDRISDB_write_json(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<CString> value,
  ) {
    return _IDRISDB_write_json(writer, index, value);
  }

  late final _IDRISDB_write_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Uint32,
            ffi.Pointer<CString>,
          )
        >
      >('IDRISDB_write_json');
  late final _IDRISDB_write_json = _IDRISDB_write_jsonPtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbWriter>, int, ffi.Pointer<CString>)
      >(isLeaf: true);

  void IDRISDB_write_byte_list(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    ffi.Pointer<ffi.Uint8> value,
    int length,
  ) {
    return _IDRISDB_write_byte_list(writer, index, value, length);
  }

  late final _IDRISDB_write_byte_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('IDRISDB_write_byte_list');
  late final _IDRISDB_write_byte_list = _IDRISDB_write_byte_listPtr
      .asFunction<
        void Function(
          ffi.Pointer<CIdrisDbWriter>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >(isLeaf: true);

  ffi.Pointer<CIdrisDbWriter> IDRISDB_write_object(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
  ) {
    return _IDRISDB_write_object(writer, index);
  }

  late final _IDRISDB_write_objectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbWriter> Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Uint32,
          )
        >
      >('IDRISDB_write_object');
  late final _IDRISDB_write_object = _IDRISDB_write_objectPtr
      .asFunction<
        ffi.Pointer<CIdrisDbWriter> Function(ffi.Pointer<CIdrisDbWriter>, int)
      >(isLeaf: true);

  void IDRISDB_write_object_end(
    ffi.Pointer<CIdrisDbWriter> writer,
    ffi.Pointer<CIdrisDbWriter> embedded_writer,
  ) {
    return _IDRISDB_write_object_end(writer, embedded_writer);
  }

  late final _IDRISDB_write_object_endPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
        >
      >('IDRISDB_write_object_end');
  late final _IDRISDB_write_object_end = _IDRISDB_write_object_endPtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
      >(isLeaf: true);

  ffi.Pointer<CIdrisDbWriter> IDRISDB_write_list(
    ffi.Pointer<CIdrisDbWriter> writer,
    int index,
    int length,
  ) {
    return _IDRISDB_write_list(writer, index, length);
  }

  late final _IDRISDB_write_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<CIdrisDbWriter> Function(
            ffi.Pointer<CIdrisDbWriter>,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('IDRISDB_write_list');
  late final _IDRISDB_write_list = _IDRISDB_write_listPtr
      .asFunction<
        ffi.Pointer<CIdrisDbWriter> Function(ffi.Pointer<CIdrisDbWriter>, int, int)
      >(isLeaf: true);

  void IDRISDB_write_list_end(
    ffi.Pointer<CIdrisDbWriter> writer,
    ffi.Pointer<CIdrisDbWriter> list_writer,
  ) {
    return _IDRISDB_write_list_end(writer, list_writer);
  }

  late final _IDRISDB_write_list_endPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
        >
      >('IDRISDB_write_list_end');
  late final _IDRISDB_write_list_end = _IDRISDB_write_list_endPtr
      .asFunction<
        void Function(ffi.Pointer<CIdrisDbWriter>, ffi.Pointer<CIdrisDbWriter>)
      >(isLeaf: true);

  int IDRISDB_web_persistence_start(ffi.Pointer<CString> directory) => 0;

  int IDRISDB_web_persistence_poll(int handle) => 1;

  int IDRISDB_web_persistence_backend() => 0;
}

final class CIDRISDBCursor extends ffi.Opaque {}

final class CIdrisDbInstance extends ffi.Opaque {}

final class CIDRISDBQuery extends ffi.Opaque {}

final class CIDRISDBQueryBuilder extends ffi.Opaque {}

final class CIdrisDbReader extends ffi.Opaque {}

final class CIdrisDbTxn extends ffi.Opaque {}

final class CIdrisDbWriter extends ffi.Opaque {}

final class CFilter extends ffi.Opaque {}

final class CIDRISDBValue extends ffi.Opaque {}

final class CString extends ffi.Opaque {}

typedef IDRISDBI64 = ffi.Int64;

final class CIdrisDbQueryCursor extends ffi.Opaque {}

final class CIDRISDBUpdate extends ffi.Opaque {}

typedef DartPort = ffi.Int64;

final class CWatchHandle extends ffi.Opaque {}

const int ERROR_PATH = 1;

const int ERROR_WRITE_TXN_REQUIRED = 2;

const int ERROR_VERSION = 3;

const int ERROR_OBJECT_LIMIT_REACHED = 4;

const int ERROR_INSTANCE_MISMATCH = 5;

const int ERROR_ENCRYPTION = 6;

const int ERROR_DB_FULL = 7;

const int AGGREGATION_COUNT = 0;

const int AGGREGATION_IS_EMPTY = 1;

const int AGGREGATION_MIN = 2;

const int AGGREGATION_MAX = 3;

const int AGGREGATION_SUM = 4;

const int AGGREGATION_AVERAGE = 5;
